// Mock Data for the application

export const dashboardMetrics = {
  totalProducts: 1284,
  currentStockValue: 142500.5, // in dollars
  todaysSales: 24,
  todaysProfit: 1250.75, // in dollars
};

export const lowStockItems = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    sku: "WH-1000XM5",
    stock: 3,
    threshold: 10,
    status: "Critical",
  },
  {
    id: "2",
    name: "Mechanical Keyboard",
    sku: "K2-V2",
    stock: 8,
    threshold: 15,
    status: "Low",
  },
  {
    id: "3",
    name: "USB-C Hub",
    sku: "HUB-C-7IN1",
    stock: 5,
    threshold: 20,
    status: "Low",
  },
  {
    id: "4",
    name: "Ergonomic Mouse",
    sku: "MX-MASTER-3",
    stock: 2,
    threshold: 10,
    status: "Critical",
  },
  {
    id: "5",
    name: "4K Monitor 27 inch",
    sku: "MON-4K-27",
    stock: 4,
    threshold: 5,
    status: "Low",
  },
];

export const recentTransactions = [
  {
    id: "ORD-7012",
    customer: "Alice Smith",
    customerInitials: "AS",
    date: "2 mins ago",
    total: 299.99,
    status: "Completed",
  },
  {
    id: "ORD-7011",
    customer: "Bob Jones",
    customerInitials: "BJ",
    date: "15 mins ago",
    total: 1049.5,
    status: "Processing",
  },
  {
    id: "ORD-7010",
    customer: "Charlie Davis",
    customerInitials: "CD",
    date: "1 hour ago",
    total: 45.0,
    status: "Completed",
  },
  {
    id: "ORD-7009",
    customer: "Diana Prince",
    customerInitials: "DP",
    date: "3 hours ago",
    total: 120.0,
    status: "Completed",
  },
  {
    id: "ORD-7008",
    customer: "Evan Wright",
    customerInitials: "EW",
    date: "5 hours ago",
    total: 850.0,
    status: "Processing",
  },
];

export const revenueData = [
  { name: "Jan", revenue: 4000 },
  { name: "Feb", revenue: 3000 },
  { name: "Mar", revenue: 2000 },
  { name: "Apr", revenue: 2780 },
  { name: "May", revenue: 1890 },
  { name: "Jun", revenue: 2390 },
  { name: "Jul", revenue: 3490 },
];

export const salesByCategoryData = [
  { name: "Electronics", value: 400, fill: "var(--color-electronics)" },
  { name: "Clothing", value: 300, fill: "var(--color-clothing)" },
  { name: "Home & Garden", value: 300, fill: "var(--color-home)" },
  { name: "Sports", value: 200, fill: "var(--color-sports)" },
];

export const mockProducts = [
  {
    id: "P-001",
    name: "Premium Wireless Headphones",
    sku: "WH-1000XM5",
    category: "Electronics",
    stock: 124,
    costPrice: 280.0,
    sellingPrice: 349.99,
    unitType: "Pieces",
    minStock: 20,
    status: "Active",
    isActive: true,
  },
  {
    id: "P-002",
    name: "Mechanical Keyboard",
    sku: "K2-V2",
    category: "Electronics",
    stock: 8,
    costPrice: 75.0,
    sellingPrice: 99.5,
    unitType: "Pieces",
    minStock: 15,
    status: "Low Stock",
    isActive: true,
  },
  {
    id: "P-003",
    name: "Cotton Crewneck T-Shirt",
    sku: "TSH-COT-BLK",
    category: "Clothing",
    stock: 540,
    costPrice: 12.0,
    sellingPrice: 19.99,
    unitType: "Pieces",
    minStock: 50,
    status: "Active",
    isActive: true,
  },
  {
    id: "P-004",
    name: "Denim Jeans",
    sku: "JNS-REG-BLU",
    category: "Clothing",
    stock: 0,
    costPrice: 30.0,
    sellingPrice: 49.99,
    unitType: "Pieces",
    minStock: 20,
    status: "Out of Stock",
    isActive: true,
  },
  {
    id: "P-005",
    name: "Ceramic Coffee Mug",
    sku: "MUG-CER-WHT",
    category: "Home & Garden",
    stock: 320,
    costPrice: 5.0,
    sellingPrice: 12.5,
    unitType: "Pieces",
    minStock: 30,
    status: "Active",
    isActive: true,
  },
  {
    id: "P-006",
    name: "Yoga Mat",
    sku: "YOG-MAT-PUR",
    category: "Sports",
    stock: 45,
    costPrice: 18.0,
    sellingPrice: 29.99,
    unitType: "Pieces",
    minStock: 10,
    status: "Active",
    isActive: true,
  },
  {
    id: "P-007",
    name: "USB-C Hub",
    sku: "HUB-C-7IN1",
    category: "Electronics",
    stock: 5,
    costPrice: 30.0,
    sellingPrice: 45.0,
    unitType: "Pieces",
    minStock: 20,
    status: "Low Stock",
    isActive: true,
  },
  {
    id: "P-008",
    name: "Running Shoes",
    sku: "SHO-RUN-GRY",
    category: "Clothing",
    stock: 112,
    costPrice: 80.0,
    sellingPrice: 120.0,
    unitType: "Pairs",
    minStock: 15,
    status: "Active",
    isActive: true,
  },
  {
    id: "P-009",
    name: "Desk Lamp",
    sku: "LMP-DSK-LED",
    category: "Home & Garden",
    stock: 84,
    costPrice: 20.0,
    sellingPrice: 35.0,
    unitType: "Pieces",
    minStock: 10,
    status: "Active",
    isActive: true,
  },
  {
    id: "P-010",
    name: "Dumbbell Set",
    sku: "DMB-SET-20",
    category: "Sports",
    stock: 0,
    costPrice: 60.0,
    sellingPrice: 89.99,
    unitType: "Sets",
    minStock: 5,
    status: "Out of Stock",
    isActive: true,
  },
  {
    id: "P-011",
    name: "4K Monitor 27 inch",
    sku: "MON-4K-27",
    category: "Electronics",
    stock: 4,
    costPrice: 220.0,
    sellingPrice: 299.0,
    unitType: "Pieces",
    minStock: 5,
    status: "Low Stock",
    isActive: true,
  },
  {
    id: "P-012",
    name: "Winter Jacket",
    sku: "JAC-WIN-BLK",
    category: "Clothing",
    stock: 25,
    costPrice: 90.0,
    sellingPrice: 150.0,
    unitType: "Pieces",
    minStock: 5,
    status: "Active",
    isActive: true,
  },
];

export const mockSuppliers = [
  {
    id: "SUP-001",
    shopName: "ElectroTech Traders",
    contactName: "David Chen",
    email: "david@electrotech.com",
    phone: "+1 (555) 123-4567",
    address: "123 Tech Boulevard, Silicon Valley, CA 94025",
    details: "Primary supplier for computer peripherals.",
    status: "Active",
  },
  {
    id: "SUP-002",
    shopName: "Global Garments Inc.",
    contactName: "Sarah Jenkins",
    email: "s.jenkins@globalgarments.net",
    phone: "+1 (555) 987-6543",
    address: "45 Fashion Ave, Suite 300, New York, NY 10001",
    details: "Bulk clothing distributor.",
    status: "Active",
  },
  {
    id: "SUP-003",
    shopName: "Home Essentials Wholesale",
    contactName: "Michael Rodriguez",
    email: "orders@homeessentials.com",
    phone: "+1 (555) 456-7890",
    address: "789 Industrial Pkwy, Chicago, IL 60601",
    details: "Delivers ceramic and plastic home goods weekly.",
    status: "Inactive",
  },
  {
    id: "SUP-004",
    shopName: "FitGear Supplies",
    contactName: "Amanda Walker",
    email: "amanda.fitgear@gmail.com",
    phone: "+1 (555) 222-3333",
    address: "200 Wellness Way, Austin, TX 78701",
    details: "Specializes in yoga mats and dumbbells.",
    status: "Active",
  },
];

export const mockPurchaseOrders = [
  {
    id: "po-init-1",
    referenceNo: "PO-00100",
    date: new Date(Date.now() - 86400000 * 2), // 2 days ago
    supplierId: "SUP-001",
    status: "Completed",
    notes: "Initial stock up",
    items: [
      {
        id: "item-1",
        productId: "P-001",
        quantity: 50,
        costPrice: 200,
        total: 10000,
      },
    ],
    subTotal: 10000,
    gstAmount: 0,
    gstPercentage: 0,
    grandTotal: 10000,
  },
  {
    id: "po-init-2",
    referenceNo: "PO-00101",
    date: new Date(),
    supplierId: "SUP-002",
    status: "Pending",
    notes: "Awaiting delivery",
    items: [
      {
        id: "item-2",
        productId: "P-003",
        quantity: 200,
        costPrice: 10,
        total: 2000,
      },
      {
        id: "item-3",
        productId: "P-004",
        quantity: 100,
        costPrice: 20,
        total: 2000,
      },
    ],
    subTotal: 4000,
    gstAmount: 0,
    gstPercentage: 0,
    grandTotal: 4000,
  },
];
